# Generated by Django 5.2.10 on 2026-01-31 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('floor_plan_image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='360_images/')),
                ('is_starting_point', models.BooleanField(default=False, help_text='Is this the first room shown in walkthrough?')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan_x', models.FloatField(blank=True, help_text='X position % on floor plan', null=True)),
                ('floor_plan_y', models.FloatField(blank=True, help_text='Y position % on floor plan', null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='viewer.house')),
            ],
            options={
                'ordering': ['house', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RoomConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(help_text='Vertical angle for hotspot in 360° view')),
                ('yaw', models.FloatField(help_text='Horizontal angle for hotspot in 360° view')),
                ('label', models.CharField(default='Go to room', max_length=100)),
                ('from_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_from', to='viewer.room')),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_to', to='viewer.room')),
            ],
            options={
                'unique_together': {('from_room', 'to_room')},
            },
        ),
    ]
