# Generated by Django 6.0.3 on 2026-04-12 14:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_house_owner_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='share_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
