# Generated by Django 6.0.3 on 2026-09-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_house_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='mission_type',
            field=models.CharField(default='Visite 360', max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Achevé', 'Achevé'), ('En retard', 'En retard')], default='En cours', max_length=50),
        ),
    ]
