# Generated by Django 6.0.3 on 2026-09-12 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_house_deadline_house_mission_type_house_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='client',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='house',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='house',
            name='official_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='house',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='reception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='wilaya',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='MissionParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='viewer.house')),
            ],
        ),
    ]
