# Generated by Django 5.1.1 on 2025-07-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='floor_plans/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_percent', models.FloatField()),
                ('y_percent', models.FloatField()),
                ('target_image', models.ImageField(blank=True, null=True, upload_to='hotspot_targets/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='floor_plan.floorplan')),
            ],
        ),
    ]
