# Generated by Django 5.2.10 on 2026-01-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='floor_plan_attachments/'),
        ),
    ]
