# Generated by Django 5.2.10 on 2026-01-31 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plan', '0002_floorplan_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='attachment_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
