# Generated by Django 5.2.10 on 2026-01-31 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plan', '0003_floorplan_attachment_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floorplan',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='attachment_label',
        ),
        migrations.CreateModel(
            name='FloorPlanAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='floor_plan_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='floor_plan.floorplan')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
