# Generated by Django 5.1.1 on 2025-07-21 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='home_thumbnails/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('visit_duration', models.DurationField(blank=True, null=True)),
                ('rooms_visited', models.JSONField(default=list)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='homeviewer.home')),
            ],
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hotspot_type', models.CharField(choices=[('navigation', 'Navigation'), ('info', 'Information'), ('media', 'Media'), ('link', 'External Link')], default='info', max_length=20)),
                ('yaw', models.FloatField(help_text='Horizontal angle in degrees (-180 to 180)')),
                ('pitch', models.FloatField(help_text='Vertical angle in degrees (-90 to 90)')),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, help_text='External URL for link hotspots')),
                ('icon', models.CharField(default='info', help_text='CSS class or icon name', max_length=50)),
                ('color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_room', models.ForeignKey(blank=True, help_text='Target room for navigation hotspots', null=True, on_delete=django.db.models.deletion.CASCADE, to='homeviewer.hotspot')),
            ],
        ),
        migrations.CreateModel(
            name='HotspotMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='hotspot_media/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hotspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='homeviewer.hotspot')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('living_room', 'Living Room'), ('bedroom', 'Bedroom'), ('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('dining_room', 'Dining Room'), ('office', 'Office'), ('garage', 'Garage'), ('outdoor', 'Outdoor'), ('other', 'Other')], default='other', max_length=20)),
                ('image_360', models.ImageField(upload_to='360_images/')),
                ('description', models.TextField(blank=True)),
                ('is_starting_room', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homeviewer.home')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='hotspot',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='homeviewer.room'),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='homeviewer.home')),
            ],
        ),
        migrations.CreateModel(
            name='TourStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration', models.PositiveIntegerField(default=10, help_text='Duration in seconds')),
                ('auto_rotate', models.BooleanField(default=True)),
                ('rotation_speed', models.FloatField(default=1.0, help_text='Rotation speed (0.1 to 5.0)')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeviewer.room')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='homeviewer.tour')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('tour', 'order')},
            },
        ),
    ]
