# Generated by Django 5.1.1 on 2025-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspotmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10),
        ),
    ]
